trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: visioncommerce-azure
  imageTag: v2
  resourceGroup: rg-visioncommerce-demo
  containerAppName: visioncommerce-app

steps:

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    containerRegistry: visioncommerce-acr
    repository: visioncommerce-azure
    dockerfile: '**/Dockerfile'
    tags: |
      v1

- task: AzureCLI@2
  displayName: Update Container App
  inputs:
    azureSubscription: visioncommerce-azure-connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp update \
        --name visioncommerce-app \
        --resource-group rg-visioncommerce-demo \
        --image acrvisioncommercezc.azurecr.io/visioncommerce-azure:v2